---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - JSON_JSONLINT
  - JSON_PRETTIER
  - PYTHON_RUFF
  - PYTHON_RUFF_FORMAT
  - TSX_ESLINT
  - TYPESCRIPT_STANDARD
  - TYPESCRIPT_PRETTIER
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
VALIDATE_ALL_CODEBASE: true
OUTPUT_DETAIL: detailed

# Linter specific configuration
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
TSX_ESLINT_CONFIG_FILE: eslint.config.js
TSX_ESLINT_COMMAND_REMOVE_ARGUMENTS: "--no-eslintrc"
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: tsconfig.json
TYPESCRIPT_STANDARD_FILTER_REGEX_EXCLUDE: vite\.config\.ts

TSX_ESLINT_PRE_COMMANDS:
  - command: pwd
    cwd: workspace
  - command: npm install
    cwd: workspace
