name: Dependabot Auto Merge

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  # ---------------------------------------------------
  # Auto-merge GitHub Actions updates
  # ---------------------------------------------------
  merge-github-actions:
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      contains(join(github.event.pull_request.labels.*.name), 'github_actions')
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.dependabot }}
          merge-method: rebase
          use-github-auto-merge: true
          skip-verification: true
  # ---------------------------------------------------
  # Auto-merge minor (and patch) updates for all other ecosystems
  # ---------------------------------------------------
  merge-semver-minor:
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      !contains(join(github.event.pull_request.labels.*.name), 'github_actions')
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.dependabot }}
          merge-method: rebase
          use-github-auto-merge: true
          target: minor # Let Fastify enforce SemVer filtering
          skip-verification: true
